# Generated by Django 3.1.6 on 2021-04-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsite_processing',
            name='result',
            field=models.CharField(blank=True, choices=[('humans', 'Humans'), ('animals', 'Animals')], max_length=10),
        ),
        migrations.AddField(
            model_name='onsite_processing',
            name='smell',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10),
        ),
        migrations.AddField(
            model_name='onsite_processing',
            name='visual',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10),
        ),
    ]
