# Generated by Django 3.1.6 on 2021-04-14 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210414_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='sid',
        ),
        migrations.AddField(
            model_name='donation_process',
            name='fid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.food_bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation_process',
            name='oid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.onsite_processing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation_process',
            name='sid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food_bank_report',
            name='fid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.food_bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onsite_processing',
            name='rid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onsite_processing',
            name='vid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.volunteer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='did',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.donor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='sid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer_report',
            name='rid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer_report',
            name='vid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.volunteer'),
            preserve_default=False,
        ),
    ]
