# Generated by Django 3.1.6 on 2021-04-15 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210414_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onsite_processing',
            name='request_time',
        ),
        migrations.AddField(
            model_name='request',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='onsite_processing',
            name='pickup_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
