# Generated by Django 3.1.6 on 2021-04-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210420_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_process',
            name='animal',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='donation_process',
            name='human',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='food_bank',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='food_item',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
