# Generated by Django 3.1.6 on 2021-04-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210421_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('On-the-way', 'On-The-Way'), ('Collected', 'Collected'), ('Donated', 'Donated')], max_length=20),
        ),
    ]
