# Generated by Django 3.1.6 on 2021-04-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210421_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='time',
            new_name='rtime',
        ),
        migrations.RemoveField(
            model_name='donation_process',
            name='time',
        ),
    ]
