# Generated by Django 3.1.6 on 2021-04-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210423_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation_process',
            name='fid',
        ),
    ]
