# Generated by Django 3.1.6 on 2021-04-27 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_donation_process_fid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
