# Generated by Django 3.1.6 on 2021-04-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210427_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsite_processing',
            name='pickup_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='rtime',
            field=models.IntegerField(null=True),
        ),
    ]
