# Generated by Django 3.1.6 on 2021-04-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210427_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_process',
            name='pics',
            field=models.ImageField(default='dafault.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='volunteer_report',
            name='pics',
            field=models.ImageField(default='dafault.jpg', upload_to='images'),
        ),
    ]
