# Generated by Django 3.1.6 on 2021-04-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210430_1124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food_Bank_Report',
        ),
    ]
