# Generated by Django 3.1.6 on 2021-05-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_donation_process_pics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer_report',
            name='pics',
        ),
    ]
