# Generated by Django 3.1.6 on 2021-05-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_volunteer_report_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Collected', 'Collected'), ('Donated', 'Donated')], max_length=20),
        ),
    ]
