# Generated by Django 3.1.6 on 2021-05-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210518_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Volunteer_Report',
            new_name='Reports',
        ),
    ]
