# Generated by Django 3.1.6 on 2021-06-12 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210518_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsite_processing',
            name='pickup_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='request',
            name='rtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
