# Generated by Django 3.1.6 on 2021-06-13 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210612_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation_process',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='donation_process',
            name='human',
        ),
    ]
